DATASET:
  type: KITTI_DATASET

KITTI_DATASET:
  type: kitti
  sensor_type: mono # Here, 'sensor_type' can be 'mono' or 'stereo'
  base_path: /home/isaac/dev/pyslam/data/KITTI
  #
  name: '10'
  settings: /home/isaac/dev/pyslam/_settings.yaml
  is_color: False # do you have the color images for the kitti dataset? (image2 and image3 folders)
  groundtruth_file: auto

SYSTEM_STATE: 
  load_state: False                # flag to enable SLAM state reloading (map state + loop closing state) and relocalization
  folder_path: /home/isaac/dev/pyslam/results/slam_state  # default folder path (relative to root of this repository) where the system state is saved or reloaded


SAVE_TRAJECTORY:
  save_trajectory: True
  format_type: kitti             # supported formats: `tum`, `kitti`, `euroc`
  output_folder: /home/isaac/dev/pyslam/results/metrics # relative to pyslam root folder 
  basename: trajectory           # basename of the trajectory saving output

GLOBAL_PARAMETERS: 
  kLogsFolder: /home/isaac/pyslam_logs       # to redirect the prints of SLAM to the set folder